project:
  type: book
  
lang: ja

book:
  title: "Rによる再現可能なデータ分析"
  author: "瓜生真也"
  date: "2024-08-29"
  chapters:
    - index.qmd
    - literacy.qmd
    - reproducibility.qmd
    - project.qmd
    - git.qmd
    - document.qmd
    - packages.qmd
    - workflow.qmd
    - container.qmd
    - reference.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
