project:
  type: book
  
lang: ja

book:
  title: "Rによるデータ分析ワークフローの効率化"
  author: "瓜生真也"
  date: "2024-08-23"
  chapters:
    - index.qmd
    - literacy.qmd
    - reproducibility.qmd
    - project.qmd
    - git.qmd
    - document.qmd
    - reference.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
