# ドキュメントの作成

データ分析の成果物はレポートやプレゼンテーションでまとめることが多いです。
その際、プログラムのソースコードとともに結果に至るまでの過程を記録しておくことは成果物の透明性を高めるために重要です。
そこで大事なのがドキュメントの作成です。
ソースコードと結果、さらに結果に対する解説や処理内容を文章にまとめることで、他の人が成果物を理解しやすくなります。
ここでは、データ分析におけるドキュメントの作成方法について紹介します。

## 文芸的プログラミング

通常のコンピュータプログラミングでは、プログラムのソースコードと実行結果は別々に扱われます。
コードと結果の関連性が失われている状態です。

例えばRの場合、スクリプトファイルにコードを書いて実行すると、コンソールに結果が表示されます。
コンソールに表示された結果をコピーして、別のファイルに貼り付けることで、ソースコードと結果を一つのファイルにまとめることができますが、コピーをし忘れたり、間違って貼り付けたりすることがあります。
またこのような作業では、データや処理内容を変更する度に上書きの必要性が生じるので手間がかかります。

文芸的プログラミングは、ソースコードと結果を含めた関連するドキュメントを一つのファイルにまとめることで、コードと結果の関連性を保ちながらドキュメントを作成する方法です。
コードの変更に伴って出力結果も自動的に更新されるため、手作業でのコピー&ペースト作業が不要になります。
このように動的に生成されるドキュメントを作成するツールとして、R MarkdownやJupyter Notebook(Jupyter)が有名です。

## Quarto

[Quarto](https://quarto.org/)はPositがオープンソースで開発している動的ドキュメント作成システムです。
Jupyterやプレーンテキストで書かれたファイルをもとに、HTMLやPDF、Wordなどのさまざまな形式でのドキュメントを作成することができます。
Rだけでなく、PythonやJuliaなどのプログラミング言語にも対応しています。

Rユーザにとっては、動的ドキュメントの作成にR Markdownを使うことが一般的ですが、QuartoはR Markdownの後継としても位置づけられています。
そのため、R Markdownの機能をほぼそのまま利用することができます。

QuartoはLinux/Ubuntu、macOS、Windowsで動作します。

### Quartoによるドキュメントの作成

Quartoでは、`.qmd`という拡張子のファイルを作成し、その中にコードと必要な文章を記述します。
`.qmd`ファイルをもとに任意の形式でのドキュメントを生成します。

`.qmd`ファイルの基本構成は以下の通りです。

- YAMLフロントマター
- 文章
- コードブロック（コードセル）[^1]

[^1]: コードを記述する箇所。Jupyterではコードセルと呼ばれる。

Jupyterを使っている場合、`.ipynb`ファイルから

### 日本語のPDF

typst
